/*
A KBase module: CGViewAdvanced
*/

module CGViewAdvanced {
    /*
        A boolean - 0 for false, 1 for true.
        @range (0, 1)
    */
    typedef int float boolean;

    /*
        An X/Y/Z style reference
    */
    typedef string obj_ref;

    /*
    required params:
    input_file: ref to Genome
    workspace_name: the name of the workspace it gets saved to

    optional params:
    linear: Genome is linear.
    gc_content: GC content shown
    gc_skew: GC skew shown
    at_content: AT content shown
    at_skew: AT skew shown
    average: GC, GC skew, AT, and AT skew plots should show the deviation of each value from the average for the entire genome.
    scale: GC, GC skew, AT, and AT skew plots should be scaled to fill the available Y-axis space on the map.
    orfs: ORFs drawn.
    combined_orfs: ORFs should drawn with forward and reverse strand represented by a separate ring.
    orf_size: The minimum length of ORFs (in codons) to show.
    tick_density: The density of the tick marks on the map.
    details: Sequence information legend drawn
    legend: Feature legend drawn
    condensed: Thin feature rings used regardless of map size.
    feature_labels: Feature labels read from the GenBank or EMBL file drawn.
    orf_labels: Labels for ORFs drawn.
    show_sequence_features: Draw features contained in the file if it is a Genbank or EMBL file.

    ref: https://github.com/happykhan/BRIG/tree/master/cgview/cgview_xml_builder
    */

    typedef structure {
        obj_ref input_file;
        boolean linear;
        boolean gc_content;
        boolean gc_skew;
        boolean at_content;
        boolean at_skew;
        boolean average;
        boolean scale;
        boolean orfs;
        boolean combined_orfs;
        int orf_size;
        float tick_density;
        boolean details;
        boolean legend;
        boolean condensed;
        boolean feature_labels;
        boolean orf_labels;
        boolean show_sequence_features;
    } CGViewInputs;

    /*
        report_name: report name generated by KBaseReport
        report_ref: report reference generated by KBaseReport
    */

    typedef structure {
        string report_name;
        string report_ref;
    } CGViewInputs;

    /*
    run_CGViewAdvanced: run CGView
    ref: http://wishart.biology.ualberta.ca/cgview/application.html
    */

    funcdef run_CGViewAdvanced(CGViewInputs params)
        returns (CGViewInputs output) authentication required;
};
